#https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/apiVersion: v1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
