apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  creationTimestamp: "2023-10-06T18:29:31Z"
  generation: 8
  name: ingress-wear-watch
  namespace: app-space
  resourceVersion: "3516"
  uid: be0367ed-2583-47a2-9dc9-68ab9590ad21
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: wear-service
            port:
              number: 8080
        path: /wear
        pathType: Prefix
      - backend:
          service:
            name: video-service
            port:
              number: 8080
        path: /watch
        pathType: Prefix
#status:
#  loadBalancer:
#    ingress:
#    - ip: 10.101.149.11
