---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-adminssion-secret
  annotations:
    kubernetes.io/service-account.name: ingress-nginx-admission
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-secret
  annotations:
    kubernetes.io/service-account.name: ingress-nginx
type: kubernetes.io/service-account-token
